2024-08-31 12:22:15,719 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Дмитрий\PycharmProjects\UrbanUniversity\Module_12\Tests_12_4.py", line 73, in test_run
    runner = Runner(2)
             ^^^^^^^^^
  File "C:\Users\Дмитрий\PycharmProjects\UrbanUniversity\Module_12\Tests_12_4.py", line 10, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-08-31 12:22:15,722 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Дмитрий\PycharmProjects\UrbanUniversity\Module_12\Tests_12_4.py", line 61, in test_walk
    walker = Runner('Walker', speed=-10)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дмитрий\PycharmProjects\UrbanUniversity\Module_12\Tests_12_4.py", line 15, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -10
